---
    when:
      - ansible_facts.os_family|lower == "debian"
      - wazuh_custom_packages_installation_agent_enabled

      - ansible_facts.os_family|lower == "redhat"
      - wazuh_custom_packages_installation_agent_enabled
      - not (ansible_facts.distribution|lower == "centos" and ansible_facts.distribution_major_version >= "8")
      - not (ansible_facts.distribution|lower == "redhat" and ansible_facts.distribution_major_version >= "8")

      - ansible_facts.os_family|lower == "redhat"
      - wazuh_custom_packages_installation_agent_enabled
      - (ansible_facts.distribution|lower == "centos" and ansible_facts.distribution_major_version >= "8") or
        (ansible_facts.distribution|lower == "redhat" and ansible_facts.distribution_major_version >= "8")