---
- name: Remove Wazuh repository (and clean up left-over metadata)
  ansible.builtin.apt_repository:
    repo: "{{ wazuh_agent_config.repo.apt }}"
    state: absent
  become: true
  changed_when: false
